// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_RACINGSCREEN_H
#define UI_RACINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_racingScreen
extern void ui_racingScreen_screen_init(void);
extern void ui_racingScreen_screen_destroy(void);
extern lv_obj_t * ui_racingScreen;
extern lv_obj_t * ui_topPanel;
extern lv_obj_t * ui_lapData;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_williamsLogo;
extern lv_obj_t * ui_tiresTemps;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

