// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_racingScreen = NULL;
lv_obj_t * ui_topPanel = NULL;
lv_obj_t * ui_lapData = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_williamsLogo = NULL;
lv_obj_t * ui_tiresTemps = NULL;
// event funtions

// build funtions

void ui_racingScreen_screen_init(void)
{
    ui_racingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_racingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_topPanel = lv_obj_create(ui_racingScreen);
    lv_obj_set_width(ui_topPanel, 310);
    lv_obj_set_height(ui_topPanel, 64);
    lv_obj_set_x(ui_topPanel, 0);
    lv_obj_set_y(ui_topPanel, 5);
    lv_obj_set_align(ui_topPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_topPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_topPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_topPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_topPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_topPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_topPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_topPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lapData = lv_obj_create(ui_topPanel);
    lv_obj_remove_style_all(ui_lapData);
    lv_obj_set_height(ui_lapData, 40);
    lv_obj_set_flex_grow(ui_lapData, 1);
    lv_obj_set_align(ui_lapData, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lapData, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_lapData, lv_color_hex(0x091C32), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lapData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lapData, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lapData, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_lapData);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -2);
    lv_obj_set_y(ui_Label1, 2);
    lv_obj_set_align(ui_Label1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label1, "0.00");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xE02121), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_lapData);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 2);
    lv_obj_set_y(ui_Label3, 2);
    lv_label_set_text(ui_Label3, "LAPS\n#");

    ui_Label2 = lv_label_create(ui_lapData);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -2);
    lv_obj_set_y(ui_Label2, -2);
    lv_obj_set_align(ui_Label2, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label2, "0.00.00");

    ui_williamsLogo = lv_img_create(ui_topPanel);
    lv_img_set_src(ui_williamsLogo, &ui_img_557436209);
    lv_obj_set_width(ui_williamsLogo, 44);
    lv_obj_set_height(ui_williamsLogo, 33);
    lv_obj_set_x(ui_williamsLogo, 0);
    lv_obj_set_y(ui_williamsLogo, 37);
    lv_obj_set_align(ui_williamsLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_williamsLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_williamsLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tiresTemps = lv_obj_create(ui_topPanel);
    lv_obj_set_height(ui_tiresTemps, 50);
    lv_obj_set_flex_grow(ui_tiresTemps, 1);
    lv_obj_set_x(ui_tiresTemps, 69);
    lv_obj_set_y(ui_tiresTemps, 40);
    lv_obj_set_align(ui_tiresTemps, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tiresTemps, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_racingScreen_screen_destroy(void)
{
    if(ui_racingScreen) lv_obj_del(ui_racingScreen);

    // NULL screen variables
    ui_racingScreen = NULL;
    ui_topPanel = NULL;
    ui_lapData = NULL;
    ui_Label1 = NULL;
    ui_Label3 = NULL;
    ui_Label2 = NULL;
    ui_williamsLogo = NULL;
    ui_tiresTemps = NULL;

}
